site_name: ConecteSUS

repo_name: "2021.2-ConecteSUS"
repo_url: "https://requisitos-de-software.github.io/2021.2-ConecteSUS/"

theme:
  name: material
  language: "pt"
  palette:
    primary: "#fff"
    accent: "light blue"
  font:
    text: "Montserrat"
    code: "sans-serif"
  logo: "assets/sus.png"
  favicon: "assets/sus.png"

nav:
  - Início: index.md
  - Planejamento:
      - Cronograma: Planejamento/Cronograma.md
      - Ferramentas: Planejamento/Ferramentas.md
      - Metodologia: Planejamento/Metodologia.md
  - Pré-Rastreabilidade:
      - Rich Picture: Pre_rastreabilidade/RichPicture.md
  - Elicitações:
      - Técnicas de elicitação:
          - Storyboard: Elicitação/Tecnicas_de_elicitacao/storyboard.md
          - Introspecção: Elicitação/Tecnicas_de_elicitacao/introspeccao.md
          - Observação Participativa: Elicitação/Tecnicas_de_elicitacao/Observacao_participativa.md
          - Brainstorming: Elicitação/Tecnicas_de_elicitacao/brainstorming.md
          - Resultados: Elicitação/Tecnicas_de_elicitacao/Resultados.md
      - Técnica de priorização:
          - Moscow: Elicitação/Tecnica_de_priorizacao/Moscow.md
      - Personas: Elicitação/Personas/personas.md
  - Modelagem:
      - Especificação Suplementar: Modelagem/Especificacao_suplementar.md
      - Cenários: Modelagem/cenarios.md
      - Léxicos: Modelagem/lexicos.md
      - Casos de Uso: Modelagem/casos_de_uso.md
      - NFR Framework: Modelagem/NFR_Framework.md
      - Ágil:
        - Histórias de Usuário: Modelagem/historias_de_usuario.md
        - Backlog: Modelagem/backlog.md
  - Análise:
      - Verificação:
        - Storyboard: Análise/Verificação/Storyboard.md
        - Cenários: Análise/Verificação/Cenarios.md
        - Histórias de Usuário: Análise/Verificação/Historias_usuario.md
        - Backlog: Análise/Verificação/Backlog.md
        - Richpicture: Análise/Verificação/Rich_picture.md
        - NFR Framework: Análise/Verificação/Nfr_framework.md
        - Moscow: Análise/Verificação/Moscow.md
        - Introspecção: Análise/Verificação/Introspeccao.md
        - Resultados: Análise/Verificação/Resultados.md
        - Especificação Suplementar: Análise/Verificação/Especificacao.md
        - Léxicos: Análise/Verificação/Lexicos.md
      - Validação:
        - Prototipação: Análise/Validação/Prototipação.md
  - Apresentações:
      - Apresentação 1: Apresentacao/Apresentacao 1.md
      - Apresentação 2: Apresentacao/Apresentacao 2.md
      - Apresentação 3: Apresentacao/Apresentacao 3.md
      - Apresentação 4: Apresentacao/Apresentacao 4.md
  - Atas:
      - 02-03-2022: Atas/02-03-2022.md
      - 07-03-2022: Atas/07-03-2022.md
