site_name: ConectaSUS

repo_name: '2021.2-ConectaSUS'
repo_url: 'https://github.com/Requisitos-de-Software/2021.2-ConectaSUS'

theme:
  name: material
  language: 'pt'
  palette:
    primary: '#fff'
    accent: 'light blue'
  font:
    text: 'Montserrat'
    code: 'sans-serif'


