site_name: ConectaSUS

repo_name: '2021.2-ConectaSUS'
repo_url: 'https://github.com/Requisitos-de-Software/2021.2-ConectaSUS'

theme:
  name: material
  language: 'pt'
  palette:
    primary: '#fff'
    accent: 'light blue'
  font:
    text: 'Montserrat'
    code: 'sans-serif'
  logo: 'assets/sus.png'
  favicon: 'assets/favicon.ico'

nav:
  - Início: index.md
  - Planejamento:
      - Cronograma: Planejamento/Cronograma.md
      - Ferramentas: Planejamento/Ferramentas.md
 
  - Apresentações:
      - Apresentação 1: Apresentacao/Apresentacao 1.md


